#!/bin/bash
# Run this after adding/removing photos to regenerate the image lists.
# Custom names and camera info are read from photo-config.json.
# Usage: ./sync-photos.sh

PHOTO_DIR="assets/Photography"
CONFIG_FILE="photo-config.json"
OUTPUT_FILE="js/photo-collections.js"

cd "$(dirname "$0")" || exit 1

echo "// Auto-generated by sync-photos.sh — do not edit manually." > "$OUTPUT_FILE"
echo "// To change names/subtitles, edit photo-config.json and re-run." >> "$OUTPUT_FILE"
echo "const photoCollections = [" >> "$OUTPUT_FILE"

find "$PHOTO_DIR" -type f \( -name '*.webp' -o -name '*.jpg' -o -name '*.jpeg' -o -name '*.png' \) | \
  sed 's|/[^/]*$||' | sort -u | while read -r dir; do

  relative="${dir#$PHOTO_DIR/}"
  category=$(echo "$relative" | cut -d'/' -f1)
  leaf=$(basename "$dir")

  # Check photo-config.json for custom name/subtitle
  config_name=""
  config_subtitle=""
  if [ -f "$CONFIG_FILE" ]; then
    escaped=$(echo "$relative" | sed 's|/|\\/|g')
    config_name=$(python3 -c "import json; d=json.load(open('$CONFIG_FILE')); print(d.get('$relative',{}).get('name',''))" 2>/dev/null)
    config_subtitle=$(python3 -c "import json; d=json.load(open('$CONFIG_FILE')); print(d.get('$relative',{}).get('subtitle',''))" 2>/dev/null)
  fi

  # Fall back to auto-generated name
  if [ -n "$config_name" ]; then
    name="$config_name"
  elif [ "$category" = "$leaf" ]; then
    name="$category"
  else
    name="${category}: ${leaf}"
  fi

  if [ -n "$config_subtitle" ]; then
    subtitle="$config_subtitle"
  else
    subtitle="$category"
  fi

  images=$(find "$dir" -maxdepth 1 -type f \( -name '*.webp' -o -name '*.jpg' -o -name '*.jpeg' -o -name '*.png' \) ! -name '.DS_Store' | sort)
  first=$(echo "$images" | head -1)

  echo "  {" >> "$OUTPUT_FILE"
  echo "    name: '${name}'," >> "$OUTPUT_FILE"
  echo "    subtitle: '${subtitle}'," >> "$OUTPUT_FILE"
  echo "    thumbnail: '${first}'," >> "$OUTPUT_FILE"
  echo "    images: [" >> "$OUTPUT_FILE"

  echo "$images" | while read -r img; do
    echo "      '${img}'," >> "$OUTPUT_FILE"
  done

  echo "    ]," >> "$OUTPUT_FILE"
  echo "  }," >> "$OUTPUT_FILE"

done

echo "];" >> "$OUTPUT_FILE"

echo "Synced photo collections → $OUTPUT_FILE"
